### ISSUE TITLE
摄像头重叠可视化的问题

### ISSUE THREAD

**Issue by liuchangji** [hou-yz/MVDet#10]
作者，您好！
   向您请教一个问题，我使用了您程序datasets/frameDatasets.py中的test()函数进行逆投影变换的可视化，把WILDTRACK数据集7个摄像头的可视化结果叠在一起是这样的，如下图：
<img width="621" alt="Figure_1" src="https://user-images.githubusercontent.com/43487003/148521254-7d6bdd38-e747-4432-8096-21612bb39433.png">
   但是在WIDETRACK数据集文章中，他给出的交叠结果是这样的：
![image](https://user-images.githubusercontent.com/43487003/148521445-20c0d57c-a36a-4124-8115-fa8cd55f38df.png)
   两张图片并不相似。我检查了每个人的position在图片中的投影，发现是没问题的。
<img width="354" alt="image" src="https://user-images.githubusercontent.com/43487003/148521873-d5ce2f3b-b48d-4daf-82fb-019e4859f03b.png">
   所以我的问题是：为什么自己显示交叠区域与论文中的差这么多呢？？这会让人怀疑是否逆透视变换正确.....

**Comment by hou-yz** [comment]
您好，
投影变化没有问题。
![image](https://user-images.githubusercontent.com/24713675/148553552-b871762e-837d-4d24-9eee-91132d0f6a64.png)
