### ISSUE TITLE
Lightweight MVDet.

### ISSUE THREAD

**Issue by zhangky666** [hou-yz/MVDet#14]
Thank you for this article, I have a great reference! Now I want to apply it to the project, using the Jetson SUB DEVELOPER KIT. Its CPU and GPU have a combined memory of 16GB, which is obviously not compatible with MVDET's requirement for two graphics cards with more than 11GB of memory. So I would like to ask if there is a MVDET lightweight approach, or is there a lightweight approach to optimize it? Hope to hear from you soon.Best wishes.

**Comment by hou-yz** [comment]
thank you for your interest!

please check out our other repo [MVDeTr](https://github.com/hou-yz/MVDeTr#architectures) and specify to use the conv architecture `python main.py -d wildtrack --world_feat conv`. this should return similar results to the vanilla MVDet and only takes one RTX 2080TI to run. 

hope this helps.

best,
Yunzhong

**Comment by zhangky666** [comment]
Thanks for your reply. When I type "python main.py -d wildtrack --world_feat conv" in the terminal, it returns ”main.py: error: unrecognized arguments: --world_feat conv“. Is there anything I missed? 

----------
usage: main.py [-h] [--reID] [--cls_thres CLS_THRES] [--alpha ALPHA] [--variant {default,img_proj,res_proj,no_joint_conv}] [--arch {vgg11,resnet18}]
               [-d {wildtrack,multiviewx}] [-j NUM_WORKERS] [-b N] [--epochs N] [--lr LR] [--weight_decay WEIGHT_DECAY] [--momentum M] [--log_interval N]
               [--resume RESUME] [--visualize] [--seed SEED]

**Comment by hou-yz** [comment]
please use the [MVDeTr](https://github.com/hou-yz/MVDeTr) repo instead of this one.
