### ISSUE TITLE
Are the detection results corresponding to the pixels obtained after NMS processing of the pedestrian occupancy map equivalent to the confidence of the anchor-based bounding box in the target detection task?

### ISSUE THREAD

**Issue by sjchhhhh** [hou-yz/MVDet#17]
Hello author, thank you very much for your work, which has brought me great inspiration. I have a question I want to know,Are the detection results corresponding to the pixels obtained after NMS processing of the pedestrian occupancy map equivalent to the confidence of the anchor-based bounding box in the target detection task?I want to optimize inference based on this work. I wonder if the average value of this probability value can be used as a performance indicator of inference results without groundtruth.Looking forward to your reply, thanks again！！！

**Comment by hou-yz** [comment]
Thank you for your interest. The txt results are the ground plane coordinate, and you can retrieve the corresponding 2D bbox for each camera view based on the `rectangles.pom` file.
