### ISSUE TITLE
What is the best way to express the performance of each frame?

### ISSUE THREAD

**Issue by sjchhhhh** [hou-yz/MVDet#18]
Hello author, thank you for your article. I have benefited a lot. I have a few questions to ask you. The final performance indicators of this task are MODA and MODP, but they are performance representations of a series of frames or the entire test set. , if I want to express the performance of each frame, which indicator do you think is more appropriate? Thank you again for your great contribution to this field, and I look forward to your reply. I wish you good luck in your work!

**Comment by sjchhhhh** [comment]
all_res.txt is the network output prior to nms, and the 4th column is the confidence. So can the average value of the confidence level of the POM occupancy probability map after NMS processing be used as a performance indicator for a certain frame?

**Comment by hou-yz** [comment]
Hi,

Thank you for the feedback. For even a single frame, I would still use the MODA, MODP, precision, and recall metrics. Just make sure that your `gt.txt` only includes data for that single frame and you should be good to go. 

The confidence values might not be the best indicator, as many research suggests that the neural networks oftentimes get over-confident with their results and there is no guarantee between high confidence and high accuracy.

Best,
Yunzhong
