### ISSUE TITLE
What is the minimum hardware requirement?

### ISSUE THREAD

**Issue by ZichengDuan** [hou-yz/MVDet#2]
Hi, could you please tell me the GPU consumption of the training? I only got two RTX2070Super at home, would it be possible to train the network with only these equipment? Many thanks

**Comment by hou-yz** [comment]
Hi,

Thank you for your interest. When the code is running, it takes 7.5GB and 5.2GB on each GPU, so it should be fine with two 2070 supers. 
Nonetheless, I don't have 2070supers at hand, so your experience may vary.

![image](https://user-images.githubusercontent.com/24713675/102575942-7e754f00-4148-11eb-8d1e-a29d2f972aa2.png)

Best,
Yunzhong

**Comment by ZichengDuan** [comment]
Hi, Yunzhong. Thank you for your attention to this issue. I have deployed the code on my PC but now I am struggling with the MATLAB engine, well, that's another issue. 😢

Anyway thanks for your information.
