### ISSUE TITLE
Pretrained model for WILDTRACK dataset

### ISSUE THREAD

**Issue by jpsml** [hou-yz/MVDet#4]
Congratulations on your work, I liked it so much! Would you be able to share a pretrained model for the WILDTRACK dataset? I do not have two GPUs available right now for training due to the COVID-19 pandemic. Best regards.

**Comment by hou-yz** [comment]
Hi,

Thank you for your interest. Please find the pretrained model at this [link](https://anu365-my.sharepoint.com/:u:/g/personal/u6852178_anu_edu_au/EdzzrGWupElCiTic-wmwzvwBnJNV52P4MQipZjt4w09pRA?e=eQAisw).

Best,
Yunzhong
