### ISSUE TITLE
大卷积核可视化

### ISSUE THREAD

**Issue by qubapikaqi** [hou-yz/MVDet#5]
请问Output: pedestrian occupancy map这个可视化在MVdet源码中有体现嘛

**Comment by hou-yz** [comment]
您好，

对pedestrian occupancy map可视化的代码请见 [link](https://github.com/hou-yz/MVDet/blob/b4da5f2a959c9772f88baea1a49f3ec06d39b839/multiview_detector/trainer.py#L133).

**Comment by qubapikaqi** [comment]
谢谢
