### ISSUE TITLE
code different

### ISSUE THREAD

**Issue by qubapikaqi** [hou-yz/MVDet#6]

**Comment by qubapikaqi** [comment]
你好，我想请问一下，我用您github上的源码跑出的moda指标最高只有83.4，而且我用您给的权重文件并不能在guthub 上下载的代码中接着训练。而且我用您log里面的代码，跑出的moda指标最高有88.7，请问您两个版本的代码有什么不同吗？
期待您的回复。

**Comment by hou-yz** [comment]
没有任何实质性区别。有更多疑问可以将断点里的代码覆盖git文件夹，用git比较不同。不能读断点因为将world_classifier改名至map_classifier。另外，请问您跑的都是wildtrack数据集么？我刚刚重跑完全可以在wildtrack上复现88左右MODA。83.4MODA十分接近multiviewx数据集上报告的结果。
