### ISSUE TITLE
Error when load checkpoint: Missing key(s) in state_dict & Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by antenna-fast** [hou-yz/MVDet#7]
Help: An error occured to me as shown in below, how to solve it?

Missing key(s) in state_dict: "map_classifier.0.weight", "map_classifier.0.bias", "map_classifier.2.weight", "map_classifier.2.bias", "map_classifier.4.weight". 

Unexpected key(s) in state_dict: "world_classifier.0.weight", "world_classifier.0.bias", "world_classifier.2.weight", "world_classifier.2.bias", "world_classifier.4.weight".

**Comment by hou-yz** [comment]
thanks for the issue and the fix. the problem was due to module renaming at a certain stage.
