### ISSUE TITLE
how to show ground plane?

### ISSUE THREAD

**Issue by Le-Cong-Hieu** [hou-yz/MVDet#8]
I'm running the code and don't know how to show the ground plane. can you show me how to show it. how can i extract the .jeson files in annotations_positions. Thanks you very much.

**Comment by hou-yz** [comment]
Hi,
Thank you for your interest. However, I don't understand your question. 
What do you mean by 'show the ground plane'? Visualization? Then please read the code for visualizations in our eccv paper. 
What json files do you mean? Json files in datasets are directly provided. Datasets are either directly downloaded (wildtrack) or not the focus of this repo (multiviewx).
Yunzhong

**Comment by Le-Cong-Hieu** [comment]
thanks for your reply.
In this article I see that in the Overview section there are 7 cameras of 2 datasets and a window showing 'ground plane' I don't know how to display it.
and i got a small error in line 84
https://github.com/hou-yz/MVDet/blob/32554fb63a044c33ca79fe85c0ea87a2d5d67ca3/multiview_detector/datasets/MultiviewX.py#L84
it gives error('NoneType' object has no attribute 'squeeze') can you show me how to fix it. Thanks a lot for your feedback.

**Comment by hou-yz** [comment]
sorry but I run on multiple platforms and none return any error at L84 in that file. can you make sure you downloaded the correct dataset? what code do you run?

**Comment by Le-Cong-Hieu** [comment]
i am running MVDet with download file checkpoints MVDet_checkpoints.zip dataset MultiviewX
I run video_visualize.py files and get that error

**Comment by hou-yz** [comment]
can you just run main.py and specify -d multiviewx? we do not provide support for the visualization codes.

**Comment by hou-yz** [comment]
and still, I don't have any error from running ```python video_visualize.py```

**Comment by Le-Cong-Hieu** [comment]
can you show me how to show 'ground plane' in Overview
Or I run main.py and it will show me

**Comment by Le-Cong-Hieu** [comment]
There may be a problem with my computer. sad

**Comment by hou-yz** [comment]
yes, video_visualize.py provides visualization. but I just don't have any error from video_visualize.py. 

please make sure you have correctly setup the dataset. it seems to me that you just have not prepared the datasets correctly, as the error from L84 in mutltiviewx.py might be called from L24, where python makes the first attempt at reading anything from that dataset folder.

**Comment by Le-Cong-Hieu** [comment]
Thanks for your feedback. I will review my data.
