### ISSUE TITLE
Unity-related questions

### ISSUE THREAD

**Issue by luorix1** [hou-yz/MVDet#9]
Hello, I am experiencing some difficulty getting from the PersonX tutorial on the official PersonX repo to achieving some likeness of your MultiviewX dataset.

Could you perhaps shed some light on how you managed all of the individual people (game objects) and their movement? I am new to Unity and somehow there doesn't seem to be that much documentation on such uses.

For example, the default PersonX code sequentially loads, moves around, and destroys the models. I tried loading multiple models using a for loop and such but they seemed to malfunction and stay in one fixed position.

Any help would be much appreciated. Thank you.

**Comment by hou-yz** [comment]
This repo is for the MVDet code. Please go to the [MultiviewX repo](https://github.com/hou-yz/MultiviewX) for related questions.
